name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
        GO111MODULE: 'on'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Determine golangci-lint version
        run: |
          GOLANG_CI_VERSION=$(head -n 1 .golangci.yml | sed 's/# //g')
      - name: Install golangci-lint
        working-directory: /tmp
        run: |
          echo "version: ${GOLANG_CI_VERSION}"
          go install "github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANG_CI_VERSION}"
      - name: Run linters
        run: |
          golangci-lint run